id: AB22588BA
title: Toh_679-Dharan%C4%AB_Praising_the_Qualities_of_the_Immeasurable_One-v2
type: translation
pechas:
- I15081BE5
- I4C0F4FC4
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-091-077
  eft-text-version: 1.1.2 2020
  title: Toh_679-Dharan%C4%AB_Praising_the_Qualities_of_the_Immeasurable_One-v2
alignment_to_base:
  I15081BE5/13F4: CB77
  I4C0F4FC4/DFCB: CB77
